name: Coursera Price Tracker

on:
  schedule:
    
    - cron: '0 15 * * *'
  push:
    paths:
      - 'data_local.json'
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    
    env:
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      GMAIL_DESTINY: ${{ secrets.GMAIL_DESTINY }}
      GMAIL_ERROR_DESTINY: ${{ secrets.GMAIL_ERROR_DESTINY }}
      COURSERA_COOKIES: ${{ secrets.COURSERA_COOKIES }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Execute Cloud Tracker
        run: python tracker_gha.py

      - name: Run Price Comparison
        run: python comparator.py
        if: always()

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json
          git commit -m "Update cloud price data [Skip CI]" || exit 0
          git push
